name: kpm-tools/shortcut-action
description: Automate story movement in Shortcut
author: kpm-tools

inputs:
  SHORTCUT_TOKEN:
    description: 'Token from Shortcut.com'
    required: true
  GITHUB_TOKEN:
    description: 'Token from GitHub.com'
    required: true
  configuration_file:
    description: 'Path to configuration file'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
