on:
  push:
  pull_request:
  pull_request_review:

jobs:
  shortcut:
    runs-on: ubuntu-latest
    name: Shortcut
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Shortcut
        uses: ./
        id: shorcut
        with:
          SHORTCUT_TOKEN: ${{ secrets.SHORTCUT_TOKEN}}
