on:
  push:
  pull_request:
  pull_request_review:

permissions: read-all

jobs:
  shortcut:
    runs-on: ubuntu-latest
    name: Shortcut
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Shortcut
        uses: ./
        with:
          SHORTCUT_TOKEN: ${{ secrets.SHORTCUT_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
